#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202111041659-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.pro
# @License       : WTFPL
# @ReadME        : template.sh --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created       : Thursday, Nov 04, 2021 16:59 EDT
# @File          : template.sh
# @Description   : template installer for ubuntu
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APPNAME="$(basename "$0")"
VERSION="202111041659-git"
USER="${SUDO_USER:-${USER}}"
HOME="${USER_HOME:-${HOME}}"
SRC_DIR="${BASH_SOURCE%/*}"
SCRIPT_DESCRIBE="template"
SCRIPT_OS="ubuntu"
GITHUB_USER="${GITHUB_USER:-casjay}"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Set bash options
if [[ "$1" == "--debug" ]]; then shift 1 && set -xo pipefail && export SCRIPT_OPTS="--debug" && export _DEBUG="on"; fi
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Vendored from casjay-dotfiles/scripts system-installer.bash (self-contained,
# no network fetch) - only the functions this script actually calls.
if [ -n "${NO_COLOR+x}" ] || [ "$SHOW_RAW" = "true" ]; then
  __printf_color() { printf '%b' "$1" | tr -d '\t'; }
else
  __printf_color() { printf "%b" "$(tput setaf "$2" 2>/dev/null)" "$1" "$(tput sgr0 2>/dev/null)"; }
fi
__printf_green() { __printf_color "$1\n" 2; }
__printf_red() { __printf_color "$1\n" 208; }
__printf_yellow() { __printf_color "$1\n" 3; }
__printf_blue() { __printf_color "$1\n" 33; }
__printf_info() { __printf_color "[ ℹ️ ] $1\n" 3; }
__printf_exit() {
  __printf_color "$1\n" 208 1>&2
  exit 1
}
__printf_success() { __printf_color "[ ✔ ] $1\n" 2; }
__printf_head() {
  [[ $1 == ?(-)+([0-9]) ]] && local color="$1" && shift 1 || local color="6"
  local msg="$*"
  shift
  __printf_color "
##################################################
$msg
##################################################\n" "$color"
}
__printf_return() {
  test -n "$1" && test -z "${1//[0-9]/}" && local color="$1" && shift 1 || local color="208"
  test -n "$1" && test -z "${1//[0-9]/}" && local exitCode="$1" && shift 1 || local exitCode="1"
  local msg="$*"
  [ ${#msg} = 0 ] || { __printf_color "$msg" "$color" 1>&2 && printf "\n"; }
  return ${exitCode:-2}
}
__printf_execute_success() { __printf_color "[ ✔ ] $1 \n" 2; }
__printf_execute_error() { __printf_color "[ ✖ ] $1 $2 \n" 1; }
__printf_execute_error_stream() { while read -r line; do __printf_execute_error "↳ ERROR: $line"; done; }
__printf_execute_result() {
  if [ "$1" -eq 0 ]; then __printf_execute_success "$2"; else __printf_execute_error "$2"; fi
  return "$1"
}
__devnull() { "$@" >/dev/null 2>&1; }
__cmd_exists() { builtin type -P "$1" &>/dev/null; }
__urlcheck() { __devnull curl --output /dev/null --silent --head --fail "$1"; }
__urlinvalid() { if [ -z "$1" ]; then __printf_red "Invalid URL\n"; else
  __printf_red "Can't find $1\n"
  exit 1
fi; }
__urlverify() { __urlcheck $1 || __urlinvalid $1; }
__setexitstatus() {
  EXIT="${EXIT:-$?}"
  local EXITSTATUS+="$EXIT"
  if [ -z "$EXITSTATUS" ] || [ "$EXITSTATUS" -ne 0 ]; then
    BG_EXIT="${BG_RED}"
    return 1
  else
    BG_EXIT="${BG_GREEN}"
    return 0
  fi
}
__set_trap() { trap -p "$1" | grep -- "$2" &>/dev/null || trap "$2" "$1"; }
__execute() {
  __kill_all_subprocesses() {
    local i=""
    for i in $(jobs -p); do
      kill "$i"
      wait "$i" &>/dev/null
    done
  }
  __show_spinner() {
    local -r FRAMES='/-\|'
    local -r NUMBER_OR_FRAMES=${#FRAMES}
    local -r CMDS="$2"
    local -r MSG="$3"
    local -r PID="$1"
    local i=0
    local frameText=""
    if [ "$TRAVIS" != "true" ]; then
      printf "\n\n\n"
      tput cuu 3
      tput sc
    fi
    while kill -0 "$PID" &>/dev/null; do
      frameText="[ ${FRAMES:i++%NUMBER_OR_FRAMES:1} ] $MSG"
      if [ "$TRAVIS" != "true" ]; then
        printf "%s\n" "$frameText"
      else
        printf "%s" "$frameText"
      fi
      sleep 0.2
      if [ "$TRAVIS" != "true" ]; then
        tput rc
      else
        printf "\r"
      fi
    done
  }
  local -r CMDS="$1"
  local -r MSG="${2:-$1}"
  local -r TMP_FILE="$(mktemp /tmp/XXXXX)"
  local exitCode=0
  local cmdsPID=""
  __set_trap "EXIT" "__kill_all_subprocesses"
  eval "$CMDS" >/dev/null 2>"$TMP_FILE" &
  cmdsPID=$!
  __show_spinner "$cmdsPID" "$CMDS" "$MSG"
  wait "$cmdsPID" &>/dev/null
  exitCode=$?
  __printf_execute_result $exitCode "$MSG"
  if [ $exitCode -ne 0 ]; then
    __printf_execute_error_stream <"$TMP_FILE"
  fi
  rm -rf "$TMP_FILE"
  return $exitCode
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[[ "$1" == "--help" ]] && __printf_exit "${GREEN}${SCRIPT_DESCRIBE} installer for $SCRIPT_OS"
cat /etc/*-release | grep -E -- 'ID=|ID_LIKE=' | grep -qwE -- "$SCRIPT_OS" &>/dev/null && true || __printf_exit "This installer is meant to be run on a $SCRIPT_OS based system"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
system_service_exists() { systemctl status "$1" 2>&1 | grep -iq -- "$1" && return 0 || return 1; }
system_service_enable() { systemctl status "$1" 2>&1 | grep -iq -- 'inactive' && __execute "systemctl enable $1" "Enabling service: $1" || return 1; }
system_service_disable() { systemctl status "$1" 2>&1 | grep -iq -- 'active' && __execute "systemctl disable --now $1" "Disabling service: $1" || return 1; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
test_pkg() {
  dpkg --get-selections "$1" 2>/dev/null | grep -qw -- "$1" &&
    __printf_success "$1 is installed" && return 0 || return 1
  __setexitstatus
  set --
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
remove_pkg() {
  aptbin=$(type -P apt || type -P apt-get)
  apt() { sudo DEBIAN_FRONTEND=noninteractive $aptbin $1 $2 -yy; }
  test_pkg "$1" &>/dev/null &&
    __execute "apt remove $1" "Removing: $1" ||
    __printf_green "$1 is not installed"
  __setexitstatus
  set --
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
install_pkg() {
  aptbin=$(type -P apt || type -P apt-get)
  apt() { sudo DEBIAN_FRONTEND=noninteractive $aptbin $1 $2 --ignore-missing -yy -qq --allow-unauthenticated --assume-yes; }
  test_pkg "$1" || __execute "apt install $1" "Installing: $1"
  __setexitstatus
  set --
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
run_update() {
  aptbin=$(type -P apt || type -P apt-get)
  apt() { sudo DEBIAN_FRONTEND=noninteractive $aptbin $1 $2 --ignore-missing -yy -qq --allow-unauthenticated --assume-yes; }
  run_external apt-get clean all
  run_external apt-get update
  run_external apt upgrade
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
detect_selinux() {
  builtin command -v selinuxenabled &>/dev/null && selinuxenabled
  if [ $? -ne 0 ]; then return 0; else return 1; fi
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
disable_selinux() {
  if builtin command -v selinuxenabled &>/dev/null && selinuxenabled; then
    __printf_blue "Disabling selinux"
    __devnull setenforce 0
  else
    __printf_green "selinux is already disabled"
  fi
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ssh_key() {
  __printf_green "Grabbing $GITHUB_USER ssh key"
  [[ -d "/root/.ssh" ]] || mkdir -p "/root/.ssh"
  if __urlverify "https://github.com/$GITHUB_USER.keys"; then
    curl -q -SLs "https://github.com/$GITHUB_USER.keys" | tee "/root/.ssh/authorized_keys" &>/dev/null &&
      __printf_green "Successfully added github ssh key" || __printf_return "Failed to add github ssh key"
  else
    __printf_return "Can not get key from https://github.com/$GITHUB_USER.keys"
  fi
  return 0
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
run_external() { __printf_green "Executing $*" && eval "$*" >/dev/null 2>&1 || return 1; }
grab_remote_file() { __urlverify "$1" && curl -q -SLs "$1" || exit 1; }
save_remote_file() { __urlverify "$1" && curl -q -SLs "$1" | tee "$2" &>/dev/null || exit 1; }
retrieve_version_file() { grab_remote_file "https://github.com/casjay-base/ubuntu/raw/main/version.txt" | head -n1 || echo "Unknown version"; }
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
run_grub() {
  __printf_green "Setting up grub"
  local grub_cnf="/boot/grub/grub.cfg"
  local grub2_cnf="/boot/grub2/grub.cfg"
  rm -Rf /boot/*rescue*
  if __cmd_exists grub2-mkconfig && [[ -f "$grub2_cnf" ]]; then
    __devnull grub2-mkconfig -o "$grub2_cnf" &&
      __printf_green "Updated $grub2_cnf"
    __printf_return "Failed to update $grub2_cnf"
  elif __cmd_exists grub-mkconfig && [[ -f "$grub_cnf" ]]; then
    __devnull grub-mkconfig -o "$grub_cnf" &&
      __printf_green "Updated $grub_cnf" ||
      __printf_return "Failed to update $grub_cnf"
  fi
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
run_post() {
  local e="$*"
  local m="${e//__devnull /}"
  __execute "$e" "executing: $m"
  __setexitstatus
  set --
}
##################################################################################################################
clear
ARGS="$*" && shift $#
##################################################################################################################
__printf_head "Initializing the installer"
##################################################################################################################
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
if [ -f /etc/casjaysdev/updates/versions/default.txt ]; then
  __printf_red "This has already been installed"
  __printf_red "To reinstall please remove the version file in"
  __printf_exit "/etc/casjaysdev/updates/versions/default.txt"
fi
if ! builtin type -P systemmgr &>/dev/null; then
  if [[ -d "/usr/local/share/CasjaysDev/scripts" ]]; then
    run_external "git -C https://github.com/casjay-dotfiles/scripts pull"
  else
    run_external "git clone https://github.com/casjay-dotfiles/scripts /usr/local/share/CasjaysDev/scripts"
  fi
  run_external /usr/local/share/CasjaysDev/scripts/install.sh
  run_external systemmgr --config &>/dev/null
  run_external systemmgr install scripts
  run_update
fi
__printf_green "Installer has been initialized"
git config --show-scope user.name 2>/dev/null | grep -q '^' || git config --global user.name "$USER"
git config --show-scope user.email 2>/dev/null | grep -q '^' || git config --global user.email "$USER@$HOSTNAME"
##################################################################################################################
__printf_head "Disabling selinux"
##################################################################################################################
disable_selinux

##################################################################################################################
__printf_head "Configuring cores for compiling"
##################################################################################################################
numberofcores=$(grep -c ^processor /proc/cpuinfo)
__printf_yellow "Total cores avaliable: $numberofcores"
if [ -f /etc/makepkg.conf ]; then
  if [ $numberofcores -gt 1 ]; then
    sed -i 's/#MAKEFLAGS="-j2"/MAKEFLAGS="-j'$(($numberofcores + 1))'"/g' /etc/makepkg.conf
    sed -i 's/COMPRESSXZ=(xz -c -z -)/COMPRESSXZ=(xz -c -T '"$numberofcores"' -z -)/g' /etc/makepkg.conf
  fi
fi
##################################################################################################################
__printf_head "Grabbing ssh key from github"
##################################################################################################################
ssh_key
##################################################################################################################
__printf_head "Configuring the system"
##################################################################################################################
run_update
install_pkg vnstat
system_service_enable vnstat
install_pkg net-tools
install_pkg wget
install_pkg curl
install_pkg git
install_pkg e2fsprogs
install_pkg lsb-release
install_pkg unzip
run_external rm -Rf /tmp/dotfiles
run_external timedatectl set-timezone America/New_York
run_update
run_grub

##################################################################################################################
__printf_head "Installing the packages for $SCRIPT_DESCRIBE"
##################################################################################################################install_pkg adduser
install_pkg apt

##################################################################################################################
__printf_head "Fixing packages"
##################################################################################################################
run_grub

##################################################################################################################
__printf_head "setting up config files"
##################################################################################################################
run_post "systemmgr install scripts"
run_post "systemmgr install ssl"
run_post "systemmgr install ssh"
run_post "systemmgr install tor"

run_post "dfmgr install bash"
run_post "dfmgr install htop"
run_post "dfmgr install misc"
run_post "dfmgr install vifm"
run_post "dfmgr install vim"

##################################################################################################################
__printf_head "Setting up services"
##################################################################################################################
#system_service_enable apache2
#system_service_disable nginx

##################################################################################################################
__printf_head "Cleaning up"
##################################################################################################################
/root/bin/changeip.sh >/dev/null 2>&1
mkdir -p /mnt/backups /var/www/html/.well-known /etc/letsencrypt/live
remove_pkg snap*

##################################################################################################################
__printf_info "Installer version: $(retrieve_version_file)"
##################################################################################################################
mkdir -p /etc/casjaysdev/updates/versions
echo "$VERSION" >/etc/casjaysdev/updates/versions/configs.txt
chmod -Rf 664 /etc/casjaysdev/updates/versions/configs.txt

##################################################################################################################
__printf_head "Finished installing for $SCRIPT_DESCRIBE"
echo ""
##################################################################################################################
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
set --
exit
# end
